#%RAML 1.0 SecurityScheme
type: x-custom
description: enforcement of the client_id and client_secret in the http header
describedBy:
  headers:
    client_id:
      type: string
      description: check _How to get access_ section
    client_secret:
      type: string
      description: check _How to get access_ section